apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: practise-pvc 
  namespace: practice
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard

