apiVersion: v1
kind: Pod
metadata:
  name: multi-pods
spec:
  containers:
    - name: fearless
      image: nginx
      ports:
        - containerPort: 80
    - name: fearlesswatch
      image: afakharany/watcher:latest