apiVersion: v1
kind: Pod
metadata: 
  name: taint-pod-nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - dev
  containers:
    - name: taint-container
      image: nginx