#remove taint-->kubectl taint nodes gke-ayyappa7997-default-pool-c9efaf59-pwcf role=dev:NoSchedule-
# add taint-->kubectl taint nodes gke-ayyappa7997-default-pool-c9efaf59-pwcf role=dev:NoSchedule
apiVersion: v1
kind: Pod
metadata: 
  name: taint-pod-nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - dev
  containers:
    - name: taint-container
      image: nginx