apiVersion: v1
kind: LimitRange
metadata:
  name: dev-team-limit-range
  namespace: dev-team
spec:
  limits:
    - type: Container
      min:
        cpu: "60m"
        memory: "68Mi"
      max:
        cpu: "120m"
        memory: "130Mi"
      default:
        cpu: "100m"
        memory: "100Mi"
      defaultRequest:
        cpu: "80m"
        memory: "80Mi"
