apiVersion: v1
kind: Pod
metadata:
  name: test-curl
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ["sleep", "3600"]
#once we login we need to give wget -qO- http://clusterip-service:8080 or 
                              # wget -qO- http://34.118.233.180:8080