apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: dynamic-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: dynamic-storage-class
