apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrole-binding 
subjects:
  - kind: User
    name: [user_name]
    apiGroup: rbac.authorization.k8s.io/v1
roleRef:
  kind: ClusterRole 
  name: clusterrole-admin #cluster role name
  apiGroup: rbac.authorization.k8s.io/v1
  