apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: practice
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/spring-asset-478912-p4/backend-app:1.0
        envFrom:
        - configMapRef:
            name: login-db-cm-01
        - secretRef:
            name: login-db-secret-01
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: practice
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 3000
